### ISSUE TITLE
PRACTICA 1 REALIDAD AUMENTADA

### ISSUE THREAD

**Issue by omarlopz** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-omarlopz#2]
[PRACTICA 1.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-omarlopz/files/6127873/PRACTICA.1.pdf)

**Comment by AxayacatlS** [comment]
Calificacion 17

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
